services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: binance-spot-signal-bot:latest
    environment:
      - ENV=dev
      - LOGBOOK_DIR=/app/data/logbook
      - CONFIG_PATH=/app/configs/config.yaml
      - CONTROL_DIR=/app/data/control
    volumes:
      - ./configs:/app/configs:ro
      - ./data/logbook:/app/data/logbook
      - ./data/control:/app/data/control
    command: ["python", "-m", "src.supervisor"]
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: binance-spot-signal-ui:latest
    environment:
      - PYTHONPATH=/app
      - LOGBOOK_DIR=/app/data/logbook
      - CONTROL_DIR=/app/data/control
    volumes:
      - ./data/logbook:/app/data/logbook
      - ./data/control:/app/data/control
      - ./src:/app/src:ro
      - ./ui:/app/ui:ro
    command: ["streamlit", "run", "ui/Home.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    restart: unless-stopped
